language: php

sudo: required

addons:
  postgresql: "9.4"

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - TEST_COVERAGE=true
        - DRIVER="pdo_mysql"
        - EXCLUDE="--exclude-group=pdo_pqsql"
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_mysql"
        - EXCLUDE="--exclude-group=pdo_pqsql"
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
        - EXCLUDE="--exclude-group=pdo_mysql"
    - php: 7.1
      env:
        - DEPENDENCIES="--prefer-lowest --prefer-stable"
        - DRIVER="pdo_pgsql"
        - EXCLUDE="--exclude-group=pdo_mysql"

before_script:
  - if [[ $DRIVER == 'pdo_mysql' ]]; then bash .travis.install-mysql-5.7.sh; fi
  - if [[ $DRIVER == 'pdo_mysql' ]]; then mysql -e 'create database event_store_tests;'; fi
  - if [[ $DRIVER == 'pdo_pgsql' ]]; then psql -c 'create database event_store_tests;' -U postgres; fi
  - composer self-update
  - composer update --prefer-source $DEPENDENCIES

script:
  - cp phpunit.xml.$DRIVER phpunit.xml
  - ./vendor/bin/phpunit $EXCLUDE --coverage-text --coverage-clover ./build/logs/clover.xml
  - ./vendor/bin/php-cs-fixer fix -v --diff --dry-run
  - ./vendor/bin/docheader check src/ tests/

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
