language: php

sudo: required

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - EXECUTE_CS_CHECK=true
        - TEST_COVERAGE=true
        - DRIVER="pdo_mysql"
    - php: 7.1
      env:
        - DEPENDENCIES="lowest"
        - DRIVER="pdo_mysql"
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.2'
    - php: 7.1
      env:
        - DEPENDENCIES="lowest"
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.2'
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.3'
    - php: 7.1
      env:
        - DEPENDENCIES="lowest"
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.3'
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.4'
    - php: 7.1
      env:
        - DEPENDENCIES="lowest"
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.4'
    - php: 7.1
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.5'
    - php: 7.1
      env:
        - DEPENDENCIES="lowest"
        - DRIVER="pdo_pgsql"
      addons:
        postgresql: '9.5'

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.local

before_script:
  - if [[ $DRIVER == 'pdo_mysql' ]]; then bash .travis.install-mysql-5.7.sh; fi
  - if [[ $DRIVER == 'pdo_mysql' ]]; then mysql -e 'create database event_store_tests;'; fi
  - if [[ $DRIVER == 'pdo_pgsql' ]]; then psql -c 'create database event_store_tests;' -U postgres; fi
  - composer self-update
  - if [[ $DEPENDENCIES == 'lowest' ]]; then composer update --prefer-source --prefer-lowest --prefer-stable; fi
  - if [[ $DEPENDENCIES != 'lowest' ]]; then composer update --prefer-source; fi

script:
  - cp phpunit.xml.$DRIVER phpunit.xml
  - ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi
  
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
