language: php

sudo: false

matrix:
  fast_finish: true
  include:
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.0
      addons:
          mariadb: '10.0'
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.0
        - DB_ATTR_ERRMODE=2 # \PDO::ERRMODE_EXCEPTION
      addons:
          mariadb: '10.0'
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.2
      addons:
          mariadb: '10.2.4'
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.2
        - DB_ATTR_ERRMODE=2 # \PDO::ERRMODE_EXCEPTION
      addons:
          mariadb: '10.2.4'
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.3
      addons:
          mariadb: '10.3'
    - php: 7.1
      sudo: true
      env:
        - DEPENDENCIES=""
        - DRIVER="pdo_mysql"
        - DB=mariadb_10.3
        - DB_ATTR_ERRMODE=2 # \PDO::ERRMODE_EXCEPTION
      addons:
          mariadb: '10.3'

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
    - $HOME/.local

before_script:
  - mkdir -p "$HOME/.php-cs-fixer"
  - phpenv config-rm xdebug.ini
  - if [[ $DB == 'mysql_5.7' ]]; then bash .travis.install-mysql-5.7.sh; fi
  - VENDOR=$(echo $DB | cut -d'_' -f 1)
  - if [[ $VENDOR == 'mariadb' ]]; then mysql -e 'SELECT VERSION();'; fi
  - if [[ $DRIVER == 'pdo_mysql' ]]; then  mysql -e 'create database event_store_tests;'; fi
  - if [[ $VENDOR == 'mariadb' ]]; then mysql -uroot -e 'GRANT ALL PRIVILEGES ON event_store_tests.* TO travis;'; fi
  - if [[ $DRIVER == 'pdo_pgsql' ]]; then psql -c 'create database event_store_tests;' -U postgres; fi
  - composer self-update
  - composer update $DEPENDENCIES

script:
  - cp phpunit.xml.$VENDOR phpunit.xml
  - if [[ $TEST_COVERAGE == 'true' ]]; then php -dzend_extension=xdebug.so ./vendor/bin/phpunit --coverage-text --coverage-clover ./build/logs/clover.xml; else ./vendor/bin/phpunit; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/php-cs-fixer fix -v --diff --dry-run; fi
  - if [[ $EXECUTE_CS_CHECK == 'true' ]]; then ./vendor/bin/docheader check src/ tests/; fi

after_success:
  - if [[ $TEST_COVERAGE == 'true' ]]; then php vendor/bin/coveralls -v; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/61c75218816eebde4486
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
