version: '2'
services:
  composer:
    image: prooph/composer:7.1
    volumes:
      - .:/app
    links:
      - postgres:postgres
      - mysql:mysql

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=event_store_tests

  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=event_store_tests
